casework/casework.github.io

- _config.yml
With all due irony, adding the `excludes` directive to support the
contribute file broke the script the contribute file provided.
The local website runner in `contribute.md` creates a directory
`vendor/bundle` at the top of the repository.  This directory was
ignored until the `exclude` was added to `_config.yml`, apparently
causing the default excludes list (commented out for illustration in
`_config.yml`) to be overwritten instead of augmented.   Jekyll started
to fail serving the local page because of an automatically generated
blog page in that bundle directory.
This patch removes the vendor/bundle directory from the website build
scan.
> Add /vendor/bundle directory to excludes

- _data/resources/references.yml
This implements a new practice - instead of attaching zips to the Git
history, add public Google Drive download links.
Zip SHA-512:
60ba326fb667ec8017e3945f75775ce51dbad5ff9aab5beaa8ffca5035a9f6e4c7f09be7e9c0b6b2c495aea550af4e44350dc247f989cafa44f88d0e7712c65d
> Add Change Proposal 7 to resources

- _config.yml
I found this URL was resolving:
https://caseontology.org/README.md
> Fix capitalization in exclude directives

- ontology/gallery/network/network_scanner.html
With the current gallery design, the Network topic needs description
This patch resolves ONT-238.
References:
* [ONT-238] ONT-190-Narrative-NetworkScanner
* [ONT-323] Add "Network" topic text to gallery page to link narratives
> Add Network Scanner narrative to Example Gallery

- ontology/gallery/urls_and_browsing_history/multiple_browsers.html
With the current gallery design, the URLs and Browsing History topic
needs description text to link this narrative.  For the sake of posting
narratives to the website, the narrative is being posted now, and will
be linked when the topic text is written.
This patch resolves ONT-218.
References:
* [ONT-218] ONT-189-Narrative-MultipleBrowsers
* [ONT-324] Add "URLs and Browsing History" topic text to gallery page
to link narratives
> Add Multiple Browsers narrative to Example Gallery

- ontology/gallery/contacts/drug_ring.html
With the current gallery design, the Contacts topic needs description
This patch resolves ONT-235.
References:
* [ONT-235] ONT-181-Narrative-DrugRing
* [ONT-327] Add "Contacts" topic text to gallery page to link narratives
> Add Drug Ring narrative to Example Gallery

- ontology/gallery/file_system/insider_threat.html
With the current gallery design, the File System topic needs description
This patch resolves ONT-236.
References:
* [ONT-236] ONT-185-Narrative-InsiderThreat
* [ONT-328] Add "File System" topic text to gallery page to link
narratives
> Add Insider Threat narrative to Example Gallery

- ontology/gallery/passwords_tokens_credentials/password_protected_files.html
With the current gallery design, the Passwords, Tokens, Credentials
topic needs description text to link this narrative.  For the sake of
posting narratives to the website, the narrative is being posted now,
and will be linked when the topic text is written.
This patch resolves ONT-237.
References:
* [ONT-237] ONT-188-Narrative-PasswordProtectedFiles
* [ONT-330] Add "Passwords, Tokens, Credentials" topic text to gallery
page to link narratives
> Add Password-Protected Files narrative to Example Gallery

- ontology/gallery/messages/whatsapp_messages.html
With the current gallery design, the Messages topic needs description
This patch resolves ONT-273.
References:
* [ONT-273] ONT-150-Narrative-WhatsAppMessages
* [ONT-331] Add "Messages" topic text to gallery page to link narratives
> Add WhatsApp Messages narrative to Example Gallery

- ontology/gallery/call_logs/whatsapp_calls.html
With the current gallery design, the Call Logs topic needs description
This patch resolves ONT-274.
References:
* [ONT-274] ONT-161-Narrative-WhatsAppCalls
* [ONT-332] Add "Call Logs" topic text to gallery page to link
narratives
> Add WhatsApp Calls narrative to Example Gallery

- ontology/gallery/installed_apps/distribution.html
With the current gallery design, the Installed Apps topic needs
description text to link this narrative.  For the sake of posting
narratives to the website, the narrative is being posted now, and will
be linked when the topic text is written.
This patch resolves ONT-302.
References:
* [ONT-302] ONT-187-Narrative-Distribution
* [ONT-333] Add "Installed Apps" topic text to gallery page to link
narratives
> Add Distribution narrative to Example Gallery

- _data/releases/migration_0_2_0/classes.tsv
- _data/releases/migration_0_2_0/kindOfRelationship_enumerants.tsv
- _data/releases/migration_0_2_0/properties.tsv
- releases/0.2.0/migration/index.html
References:
* [ONT-231] (CP-10) Definition of Trace from CASE prototype not
preserved
* [ONT-281] (CP-9) Adoption of Investigation namespace from UCO into
CASE
* [ONT-353] Review migration guide against release-0.2.0 branch
* [UCO Issue 75] Refactor how vocabularies are defined
https://github.com/ucoProject/UCO/issues/75
* [UCO Issue 143] Casing correction - "picturetype"
https://github.com/ucoProject/UCO/issues/143
> Update migration guide for changes from release-0.2.0 branch

- examples/asgard/index.html
This patch squash-commits the changes made to the Asgard example in the
ONT-352 branch, except for linking to the asgard.json file.  I would
prefer to provide that file only when it can be easily synchronized with
the JSON rendered in the HTML.
ONT-352 is not being merged yet because it builds on ONT-356, and 356
will take some discussion before merging.
References:
* [ONT-231] (CP-10) Definition of Trace from CASE prototype not
preserved
* [ONT-352] Test website examples against release-0.2.0 branch
* [ONT-356] Prepare "Asgard" JSON-LD for querying
> Update Asgard example for CASE release-0.2.0

- _data/nav.yml
- _data/releases/releases.yml
- releases/0.3.0/index.md
I confirmed the navigation bar, the archive page, and the new, empty
0.3.0 page are navigable and render as one would expect.
References:
* [ONT-359] Update website release links for 0.2.0
> Update website release links for 0.2.0

- .github/workflows/web_resources.yml
This workflow executes steps I have been using to confirm data-driven
files, built for serving on Github's Jekyll service, are synchronized
with their source files.  Actual instructions to run tests in each
directory were encoded in Makefiles prior to this patch.
This patch addresses part of ONT-360: Establishing the CI framework.
A follow-on patch will add narrative page building, somewhat abstracted,
to the Make build chain.
Please note this disclaimer related to mention of specific software:
Participation by NIST in the creation of the instructions for this
software is not intended to imply a recommendation or endorsement by the
National Institute of Standards and Technology, nor is it intended to
imply that any specific software is necessarily the best available for
the purpose. …
> Add Github Action for Continuous Integration checks

- examples/urgent_evidence/Makefile
- examples/urgent_evidence/index.html
- examples/urgent_evidence/index.html.in
- examples/urgent_evidence/test_urgent_evidence.py
- examples/urgent_evidence/urgent_evidence-query-exhibit_photos.sparql
- examples/urgent_evidence/urgent_evidence.json
- requirements.txt
This patch adds the following:
* A rudimentary definition of the subject device.  Intentionally, no
descriptors are provided save it has a Device facet.
* Definitions of two analytic tools already noted in the narrative, the
camera and the analytic kiosk.
* Definitions of the six photograph files taken of the device.
* Definition of a single photograph file extracted from the device as
part of the kiosk analysis.  This is to supply ground truth negative,
a potentially-confused file, for a query for photographs of the
evidence.
* A test for picture files for photographs of the device, excluding a
picture file extracted from the device.
This patch adds a new dependency on pytest to the top virtual
environment, to test the query results.
This patch will potentially require a follow-on patch …
> Implement and test query for photographs of exhibits

- examples/urgent_evidence/index.html
- examples/urgent_evidence/index.html.in
- examples/urgent_evidence/urgent_evidence-query-exhibit_photos.sparql
- examples/urgent_evidence/urgent_evidence.json
From discussion on UCO CP-22 this morning, the UCO OC opted to provide
guidance on annotating investigative devices, and to rely on the
observable namespace to provide camera properties and designation.
References:
* [ONT-367] Query - photographs of exhibits (Urgent Evidence, Narrative
ONT-118)
* [UCO OC-75] (CP-22) Add Camera class to Tool namespace
> Remove hard-coded camera identifier

- examples/urgent_evidence/index.html
- examples/urgent_evidence/urgent_evidence.json
- src/sample_sparql_runner.py
The XML Schema datatypes prefix is "xs:" in some RDF frameworks, "xsd:"
in others.  If not specified, a framework may assume the default-looking
prefix it doesn't use is an arbitrary string.
References:
* [AC-154] XML Schema datatype prefix needs to be explicit in all
examples
> Assign prefix for XML Schema

- ontology/testing_versioned_iris_case/case
- ontology/testing_versioned_iris_case/investigation
These files are temporary, and are expected to be retracted after
completion of ONT-64.
References:
* [ONT-64] (CP-17) Define scheme for CASE and UCO importable versioned
IRIs
* [ONT-412] (CP-26) Implement versionIRI in CASE 0.2.0
> Add demonstration ontologies for website-based retrieval

- assets/css/topics.css
- examples/topics.html
The current breaking for investigative action is:
case-
investigation:Investi
gativeAction
This CSS adjustment removes padding and sets the minimum column width to
be content-controlled, based on longest prefixed IRI.
Visually tested with Firefox in Ubuntu, and Firefox, Chrome, and Safari
in macOS.
> Expand topics table's IRI column width to prevent line breaks

- resources/instance_data.html
References:
* [AC-134] Document IRI usage of hash vs. slash
> Fix HTML typo

- ontology/gallery.html
One oversight from implementation of ONT-354 was that there were at
least two external locations that linked to the examples gallery at its
prior location, one of which will not be an immediate correction.  While
those external links are being corrected, we should have a redirect in
place.
This page can be deleted after some period where we believe the
corrected links have had a chance to propagate.
A few implementation answers were found while searching for syntax
reference.
References:
* https://stackoverflow.com/a/19717455
* https://oktomus.com/posts/2019/github-pages-redirect-any-link/
* [ONT-354] The examples on the website need a unified index and layout
revision
* [ONT-442] (CP-37) The ontology repository's README includes a broken
link to the website examples gallery …
> Add redirect from prior gallery URL

- .github/workflows/web_resources.yml
- Makefile
References:
* [AC-195] Use Python venv instead of virtualenv to build virtual
environments for CI
> Use Python venv to build virtual environment for CI

- Makefile
The 3.command of this OR ladder accidentally redirected stderr to
`dev/null` instead of `/dev/null`.
> Select Python3.9 if available, and fix syntax on 3.6 fallthrough

- .gitignore
This QOL PR will adjust the gitignore file to ignore the __pycache__ folder in examples/urgent_evidence.
> Ignore __pycache__ from urgent_evidence example

- resources/charter.md
Adds hyperlinks to HTTP links that didn't have proper hyperlink in the charter.
> Add Hyperlinks to Remaining Links

- Makefile
This silences the notices that the "legacy setup.py" is used when `pip`
installs from local directories.
References:
* [AC-195] Use Python venv instead of virtualenv to build virtual
environments for CI
> Include wheel in venv build

- examples/Makefile
This was manifesting in weird behaviors in the asgard/ directory when
running `make -j` (parallel builds).
> Fix copy-paste error

- _data/releases/releases.yml
- releases/0.2.1/index.md
* Created new 0.2.1 directory in 'releases/'
* Updated 'releases.yml'
Apparently, modifications have also been made to 'dependencies/CASE-Utilities-Python', but not by me.
> Create release page for CASE 0.2.1

- examples/src/example-src.mk
- examples/urgent_evidence/index.html
- examples/urgent_evidence/src/query-exhibit_photos.sparql
- examples/urgent_evidence/src/test_urgent_evidence.py
- examples/urgent_evidence/src/urgent_evidence_base.json
- examples/urgent_evidence/urgent_evidence.json
The CASE-Examples-QC repository includes a step that converts example
JSON-LD to Turtle.  This had not yet been run when testing the upgrade
of rdf-toolkit to the post-1.10 state.  Not having done so, we missed
that there is a potential build-halting issue with `rdf-toolkit`.
The current version of `rdf-toolkit` contains a behavior (possibly a
bug) that dislikes this snippet of JSON-LD:
```json
{
"@id": "urn:example:kb:object-1",
"@type": "owl:Thing",
"uco-core:hasFacet": {
"@type": "uco-core:Facet"
}
}
```
The blank node that contains only a type assertion raises a
`NullPointerException` in a step related to determining sort order of
blank nodes.
A follow-on patch will remove one occurrence of this behavior, as it
turns out to be unhelpful data (an empty `DeviceFacet`).  Before the …
> Confirm Turtle translation ability

- _data/nav.yml
Add the documentation (https://ontology.caseontology.org/case/documentation/index.html) to the Ontology menu of the CASE website.
> Add Ontology Documentation to Menu

- _data/nav.yml
- _data/releases/releases.yml
- releases/0.8.0/index.md
- Add 0.8.0 placeholder page
- Add 0.7.0 release to releases list
- Point "Current Release" to 0.7.0
> Bump 0.7.0 Release References

- examples/asgard/asgard.json
- examples/asgard/src/asgard-supplements.json
`uco-identity:Role` does not exist.  `uco-role:Role` does, but CASE has a more specific subclass that would be more appropriate to use here.
This PR is only a correction of a class reference.  Further discussion needs to be had on whether `role:Role` is appropriate to use as an object of the `action:performer` property.  I believe this usage is incongruous with other ontologies outside of UCO.
> Correct class reference

- examples/hardware_duplicator/hardware_duplicator.json
- examples/hardware_duplicator/index.html
- examples/hardware_duplicator/src/Makefile
- examples/hardware_duplicator/src/hardware_duplicator-evidential_item.json
- examples/hardware_duplicator/src/hardware_duplicator-forensic_acquisition_results.json
- examples/hardware_duplicator/src/hardware_duplicator-investigative_action.json
- examples/hardware_duplicator/src/hardware_duplicator-partition_structure.json
- examples/hardware_duplicator/src/hardware_duplicator_base.json
- examples/hardware_duplicator/src/hardware_duplicator_json.py
- examples/hardware_duplicator/src/index.html.in
This patch series updates the Hardware Duplicator example to regenerate from source files.  I noticed this was necessary when observing a slight data error that, when corrected, should have propagated to the `index.md` file, but didn't because that file was still in a state of copy-paste management.
> Restructure Hardware Duplicator example

- .gitmodules
- Makefile
This patch adds the ability to run a single command to handle checking all direct-dependencies within `pre-commit` and Git submodules.
While some other CASE repositories run this command nightly, this patch leaves that as a future decision due to current testing procedures within the CASE and UCO ontology repositories.
> Add supply-chain review target

- .gitignore
- Makefile
The first commit documents this PR's purpose.
As a matter of Make orchestration programming, I will handle merging this myself once CI passes.  I've already run this once after bumping submodule pointers around and was satisfied with the rebuild steps.
> Revise Make descent order

- examples/asgard/src/asgard_json.py
- examples/crossover_heist/src/crossover_heist_json.py
- examples/crossover_wmd/src/crossover_wmd_json.py
- examples/hardware_duplicator/src/hardware_duplicator_json.py
- examples/owl_trafficking/src/owl_trafficking_json.py
- examples/src/example-basedir.mk
- examples/src/example-src.mk
The commit messages document this PR's purpose.  This is an aid to offline development.
As a matter of Make orchestration programming, I will handle merging this myself once CI passes. I've been exercising this by deleting various files and running and re-running `make` or `make check`, and I'm satisfied with the rebuild steps.
> Remove redundant example rebuilds

- examples/.gitignore
- examples/Makefile
- examples/crossover_heist/crossover_heist.json
- examples/crossover_heist/index.html
- examples/crossover_heist/src/crossover_heist-web_browser_history_wow_usb.json
- examples/crossover_wmd/crossover_wmd.json
- examples/crossover_wmd/index.html
- examples/crossover_wmd/src/crossover_wmd-email.json
- examples/crossover_wmd/src/crossover_wmd-reddit_account.json
- examples/crossover_wmd/src/crossover_wmd-sim_card_properties.json
- examples/crossover_wmd/src/crossover_wmd-url_history.json
- examples/crossover_wmd/src/crossover_wmd-users_and_accounts.json
- examples/crossover_wmd/src/crossover_wmd-whatsapp_file_forensic_copy_relationship.json
- examples/crossover_wmd/src/crossover_wmd-whatsapp_file_msgstore_db.json
- examples/crossover_wmd/src/crossover_wmd-whatsapp_message_file_relationship.json
- examples/owl_trafficking/index.html
- examples/owl_trafficking/owl_trafficking.json
- examples/owl_trafficking/src/owl_trafficking-01.json
- examples/owl_trafficking/src/owl_trafficking-02.json
- examples/owl_trafficking/src/owl_trafficking-04.json
- examples/owl_trafficking/src/owl_trafficking-06.json
- examples/owl_trafficking/src/owl_trafficking-09.json
- examples/owl_trafficking/src/owl_trafficking-10.json
- examples/owl_trafficking/src/owl_trafficking-15.json
- examples/owl_trafficking/src/owl_trafficking-18.json
- examples/owl_trafficking/src/owl_trafficking-supplements.json
- examples/postvisit.mk
- examples/test_kb_casework_github_io_examples.py
This is part of implementing [CASE-Examples-QC PR 54](https://github.com/ajnelson-nist/CASE-Examples-QC/pull/54).
This PR is built on top of [PR 293](https://github.com/casework/casework.github.io/pull/293).
> Test for IRIs that share UUIDs

- Dockerfile
The `jekyll-build-pages` GitHub Action today uses Ruby 3.3, and has since 2024-08-06.
References:
* https://github.com/actions/jekyll-build-pages/blob/b55ba671954459b92b0cd26dacd80f7deaedecaa/Dockerfile#L1
> Bump Dockerfile to use Ruby 3.3

- docker-compose.yml
References:
* https://docs.docker.com/reference/compose-file/version-and-name/#version-top-level-element-obsolete
> Remove deprecated version declaration

- Gemfile.lock
Commands run, in a local Ubuntu 22.04 instance:
```bash
bundle config set --local path 'vendor/bundle'
bundle install
```
These updates seem satisfiable, per:
```bash
bundle check --dry-run --gemfile Gemfile
```
That `check` command was failing prior to this patch.
References:
* https://github.com/actions/jekyll-build-pages/blob/e9ec94b518184f806907923eaeb6bc69294b0bce/entrypoint.sh#L15
> Refresh Gemfile.lock

- .github/workflows/jekyll.yml
Converts the build flow away from the native Jekyll workflow and to the Jekyll website packaging to allow for custom plugins and version upgrades.
https://jekyllrb.com/docs/continuous-integration/github-actions/
> Jekyll Workflow Migration

- .github/workflows/docker_compose_ci.yml
- .github/workflows/jekyll.yml
This PR addresses #315 , at least in part.  Instead of depending on the Docker scaffolding review workflow and the content-reviewing workflow, this PR has Jekyll deployment depend on just the Docker scaffolding review workflow of #318 .
This PR is built on #318 .  Merging it will automatically merge 318 if it isn't merged already.
> Have deployment workflow depend on testable docker

- ontology/get-started.md
In case the `Cargo.toml` details are needed later, these are the contents used to confirm the added examples compile and run:
Basic Graph Creation:
```toml
[package]
name = "temp_graph_creation_example"
version = "0.1.0"
edition = "2024"
[dependencies]
json-ld = "0.21.1"
serde_json = "1.0.140"
uuid = {version = "1.16.0", features = ["v4"]}
```
Query CASE Graphs:
```toml
[package]
name = "temp_query_example"
version = "0.1.0"
edition = "2024"
[dependencies]
iref = "3.2.2"
json-ld = "0.21.1"
oxigraph = { version = "0.4.1", default-features = false}
static-iref = "3.0.0"
tokio = { version = "1.41.1", features = ["macros", "rt-multi-thread", "test-util"] }
```
Disclaimer:
Participation by NIST in the creation of the documentation of mentioned software is not intended to imply a recommendation …
> Add Rust to Get Started

- examples/crossover_wmd/crossover_wmd.json
- examples/crossover_wmd/index.html
- examples/crossover_wmd/src/crossover_wmd-report_generation.json
A recent RDFLib parser update changed the parsed value of the modified timestamp as follows:
```patch
-       uco-observable:observableCreatedTime "2020-05-16T10:12:24+00:00"^^xsd:dateTime ;
+       uco-observable:observableCreatedTime "2020-05-16T10:12:00.400000+00:00"^^xsd:dateTime ;
```
> Fix timestamp typo
