- _data/community/meetings.yml
- _data/community/presentations.yml
- _data/nav.yml
- assets/css/presentations.css
- assets/js/presentations.js
- community/presentations.html
Added a section to the website with various slide decks for presentations and workshops over the years. Also added slides for previous meeting that only had recordings associated with them.
> Added presentations and workshops section

- _data/community/meetings.yml
- assets/css/meetings.css
- assets/css/presentations.css
- community/meetings.html
Added meeting minutes for GC and AC. Also updated the HTML and CSS code on the meeting minutes page to allow for Adoption Committee meetings to be represented
> Updated meeting minutes (GC & AC). Updated css and html for AC

- resources/bylaws.md
Updated bylaws with newly ratified ones. Also removed bylaw feedback period notice.
> Updated bylaws

- ontology/start.html
This mapping guide updates: JSON-LD examples
> Updating Mapping Guide link for v0.3 of the Mapping Guide 

- ontology/gallery/email/phishing.html
This patch updates the implementation of ONT-219.
References:
* [ONT-219] ONT-146-Narrative-Phishing
> Correct copy-paste error in page title

- ontology/releases/0.2.0/migration/index.html
This is a trivial fix, there is no backing Jira ticket.
> Fix namespace prefix typo

- _data/resources/references.yml
Links have been added to references.yml to display the order in which
their branches and tickets will be resolved in Jira.  The last proposal
to be resolved is the top listed proposal in the references table.
Proposal 2 PDF SHA-512:
b3b2ad066d367eed693b8f0f5b0b72b68c2a1d4b68a42e38119d91bbe1a022703204234222e129f004de9463c56265a9a259a914477d4e565995b880b847bf50
Proposal 4 Zip SHA-512:
55523c0ac303154314d72f8ca434b6f883e2d1ecbe1445e2c0abe69f8faf74389b3b9d00aedbf6dbea95da10dab67abe45cf8365516ced5ad9126d33fed14ad6
Proposal 6 PDF SHA-512:
965968325aa89c62d139a09f4e317b403158b5e1e3a7cab93d7998114c5428fa25b791830febe4df394a368681c8dabbb9ffbc20ef5569c173bae07b9104b753
Proposal 9 Zip SHA-512:
ea73dd020d96d51e7c12c7ea2429a6d3ae281f0d316250329228ad6c9faaa4e7e717146ec5415011bd1b5f77cabeb07f0f55d2b0ea7e …
> Add Change Proposals for CASE 0.2.0 to resources

- ontology/releases/0.2.0/migration/index.html
References:
* [ONT-297] Update UCO imports to UCO 0.4.0
> Update UCO import in migration guide to UCO 0.4.0

- examples/asgard/index.html
A squash-commit accident linked a file not yet being provided.
This file will be coming on resolution of ONT-356.
References:
* [ONT-356] Prepare "Asgard" JSON-LD for querying
> Remove link to file not yet provided

- releases/0.2.0/index.html
> Update release date

- _data/releases/migration_0_2_0/classes.tsv
- releases/0.2.0/migration/classes.csv
- releases/0.2.0/migration/classes.tsv
References:
* [ONT-364] Add CASE 0.2.0 migration updates from device.json
Reported-by: Tom Anderson <tom.anderson@nuix.com>
Reviewed-by: Alex Nelson <alexander.nelson@nist.gov>
> Add migration updates from migrating device.json

- _data/releases/migration_0_2_0/classes.tsv
- _data/releases/migration_0_2_0/properties.tsv
- releases/0.2.0/migration/classes.csv
- releases/0.2.0/migration/classes.tsv
- releases/0.2.0/migration/properties.csv
- releases/0.2.0/migration/properties.tsv
This patch came from resolving CASE Jira AC-82.
References:
* [AC-82] Migrate CASE example from prototype - message.json
> Add migration steps learned from message.json

- _data/releases/migration_0_2_0/classes.tsv
- _data/releases/migration_0_2_0/properties.tsv
- releases/0.2.0/migration/classes.csv
- releases/0.2.0/migration/classes.tsv
- releases/0.2.0/migration/properties.csv
- releases/0.2.0/migration/properties.tsv
This patch came from resolving CASE Jira AC-83.
References:
* [AC-83] Migrate CASE example from prototype -
mobile_device_and_sim_card.json
> Add migration steps learned from mobile_device_and_sim_card.json

- _data/releases/migration_0_2_0/kindOfRelationship_enumerants.tsv
- releases/0.2.0/migration/kindOfRelationship_enumerants.csv
- releases/0.2.0/migration/kindOfRelationship_enumerants.tsv
References:
* [AC-121] Update enumerants of CASE-Examples for migration guide for
CASE 0.2.0
> Add all remaining unmigrated enumerants of CASE-Examples

- _data/releases/migration_0_2_0/classes.tsv
- _data/releases/migration_0_2_0/properties.tsv
- _data/releases/migration_0_2_0/properties_ambiguous.tsv
- releases/0.2.0/migration/classes.csv
- releases/0.2.0/migration/classes.tsv
- releases/0.2.0/migration/properties.csv
- releases/0.2.0/migration/properties.tsv
- releases/0.2.0/migration/properties_ambiguous.csv
- releases/0.2.0/migration/properties_ambiguous.tsv
This patch came from resolving CASE Jira AC-85.
References:
* [AC-85] Migrate CASE example from prototype - sms_and_contacts.json
> Add migration steps learned from sms_and_contacts.json

- examples/location_geo_coords/index.html
Added the Location/GeoLocation Coordinates narrative to the Example Gallery.
Signed-off by: Trevor Bobka <tbobka.mitre@gmail.com>
> Adds Location/Geo Coordinates narrative to Gallery

- examples/document_forensics/index.html
- examples/scholastic_test_key/index.html
Added the Cheating on State Test narrative to the Example Gallery.
Signed-off by: Trevor Bobka <tbobka.mitre@gmail.com>
> Adds Documents narrative to Gallery

- _data/nav.yml
- resources/github_repos.md
References:
* [AC-93] Publish policy on repository naming and status
> Add GitHub repository naming page

- examples/asgard/asgard.json
- examples/asgard/asgard_0.json
- examples/asgard/asgard_1.json
- examples/asgard/asgard_2.json
- examples/asgard/asgard_3.json
- examples/asgard/asgard_4.json
- examples/asgard/asgard_5.json
- examples/asgard/index.html
- examples/urgent_evidence/urgent_evidence.json
References:
* [ONT-372] Blank terms cannot be used in JSON-LD, but the examples use
"" as a knowledge base prefix
> Replace blank knowledge base prefix with "kb"

- examples/urgent_evidence/index.html
- examples/urgent_evidence/urgent_evidence.json
References
* [ONT-387] Query - actions taken to derive artifact (Urgent Evidence,
Narrative ONT-118)
> Integrate exhibit kiosk-disconnection as conclusion of processing action

- examples/urgent_evidence/urgent_evidence.json
References
* [ONT-341] MVP JSON-LD for Urgent Evidence (Narrative ONT-118)
> Update missed node name change

- examples/urgent_evidence/urgent_evidence.json
This is part of provenance record documentation forthcoming in a FAQ
entry.
References:
* [AC-135] Document how to represent an evidence handoff with provenance
records
* [ONT-387] Query - actions taken to derive artifact (Urgent Evidence,
Narrative ONT-118)
> Use recent provenance records as chain progresses

- resources/bylaws.md
Formatting issues corrected leftover from markdown conversion.
> Updated formatting on bylaws markdown (WEB-52)

- _data/nav.yml
- _data/resources/faq.yml
- resources/faq.html
Related to AC ticket 128:
https://case.atlassian.net/browse/AC-128
> Added FAQ pages & nav links

- _data/resources/github_repos.yml
References:
* [WEB-53] Refresh implementations status, 2021-02-17
> Refresh implementations status

- _data/nav.yml
- resources/instance_data.html
References:
* [AC-134] Document IRI usage of hash vs. slash
> Transcribe Instance Data Guidance page

- _config.yml
Fixed word in the description in _config.yml (Anaylsis -> Analysis).
> Updated CASE website description text

- _data/resources/references.yml
Proposal 16 PDF SHA-512:
ad1da2b79e139535c4d34abcfe3aebb67f54c58121ecfc0381d8888e5b0d77d7e70426acb8ccf94399fbf1627d887a96db293b172f24c0892accfc83c1b11c4c
References:
* [ONT-251] (CP-16) Establish unit tests, possibly Continuous
Integration, for ontology repository
> Add Change Proposal link for CASE CP-16

- _data/resources/references.yml
Proposal 25 PDF SHA-512:
c2eeab1ce9a4f8eb04f8ed8234d15062b033cb7f2b32e8ff8b53ba4b788ff7c15db226a7e44bb4ffd5c833da170c6595de117afab7ff7b6160f974db2a6a9600
References:
* [ONT-413] (CP-25) CASE is missing prefix statements for imported UCO
namespaces and concepts
> Add Change Proposal link for CASE CP-25

- _data/resources/references.yml
Proposal 15 PDF SHA-512:
ab83107bfbe9a2c30679abed62168941288628b525b0ee74f0b30469907fba6363a90035026c69840b7cbcada3b1abe1d83d78f8bd819bf22e0ead34791fab6a
References:
* [ONT-363] (CP-15) Remove intermediate role classes
> Add Change Proposal link for CASE CP-15

- _data/resources/references.yml
Proposal 18 zip SHA-512:
faf9d5413152aa21db5b16197e2a5d8cf59539ef4ba86890ddeb7d6da4bcc569bf6bfcab9be5a8bc004f4846731fd34d32d54ce6ae6339d36348eb239a4d5fdc
References:
* [ONT-379] (CP-18) Class definition comments in Investigation namespace
need to be updated for clarity and consistency
> Add Change Proposal link for CASE CP-18

- _data/nav.yml
- examples/index.html
Updated the gallery page to include only examples that have JSON-LD backing them.
Urgent Evidence
Owl Trafficking
Asgard
> ONT-354 - Restructured gallery page

- _data/resources/github_repos.yml
References:
* [AC-159] Publish Python Utilities repository
* [ONT-391] Map CASE to PROV-O
> Update repositories page

- examples/urgent_evidence/test_urgent_evidence.py
References:
* [ONT-367] Query - photographs of exhibits (Urgent Evidence, Narrative
ONT-118)
> Add NIST disclaimer

- examples/topics.html
- examples/urgent_evidence/index.html
- examples/urgent_evidence/index.html.in
References
* [ONT-387] Query - actions taken to derive artifact (Urgent Evidence,
Narrative ONT-118)
> Document wasInformedBy on topics gallery

- _data/resources/faq.yml
- resources/faq.html
Migrated text FAQ items from https://case.atlassian.net/wiki/spaces/AC/pages/528777228/Frequently+Asked+Questions+FAQ
> Migrate FAQ page from wiki to website

- _data/resources/faq.yml
Updated spelling and provided additional information for some FAQ items.
> FAQ update

- _data/resources/faq.yml
References:
* [AC-139] FAQ question - Does CASE require hex data be entered
uppercase or lowercase?
> Add link to test on hexBinary

- examples/topics.html
References:
* [ONT-431] Document rootExhibitNumber and exhibitNumber on topics
gallery
> Fix HTML tag error and entity usage

- community/adopters.html
- ontology/intro.md
- Add new page for adopters
- Change link to adopters
> Add Adopters Page

- .gitmodules
- Makefile
- dependencies/.gitignore
- dependencies/Makefile
- examples/asgard/src/asgard_validation-develop.ttl
- examples/asgard/src/asgard_validation-unstable.ttl
- examples/crossover/src/crossover_validation-develop.ttl
- examples/crossover/src/crossover_validation-unstable.ttl
- examples/owl_trafficking/src/owl_trafficking_validation-develop.ttl
- examples/owl_trafficking/src/owl_trafficking_validation-unstable.ttl
- examples/src/example-src.mk
- examples/urgent_evidence/src/urgent_evidence_validation-develop.ttl
- examples/urgent_evidence/src/urgent_evidence_validation-unstable.ttl
This patch series copies the resulting implementation from CASE-Examples PR 43, so the two example sets can use the same prelease-review process.
> Add prerelease engineering

- examples/topics.html
References:
* [ONT-435] (CP-34) Revise ontology IRI to be slash-based and drop
resource-type
> Revise CASE IRI structure in documentation

- examples/asgard/src/asgard_validation-unstable.ttl
- examples/crossover/src/crossover_validation-unstable.ttl
- examples/owl_trafficking/src/owl_trafficking_validation-unstable.ttl
- examples/urgent_evidence/src/urgent_evidence_validation-unstable.ttl
A local command-line error staged the wrong submodule pointer.
> Re-bump CASE-unstable to pick up resolution of ONT-435

- _data/releases/releases.yml
References:
* [ONT-463] Release CASE 0.6.0
> Align release date

- .gitmodules
This PR also implements a (fortunately uneventful) test for [UCO PR 344](https://github.com/ucoProject/UCO/pull/344).
> Use -Archives repositories instead of ajnelson-nist forks

- examples/owl_trafficking/owl_trafficking.json
- examples/owl_trafficking/src/owl_trafficking-03.json
> Owl example msisdn

- CONTRIBUTE.md
At last week's Ontology Committees meeting, there was a request to update the contribution directions with notes on the implemented review process.
If this text is fine, please feel free to merge, and I will start porting it over to CASE-Examples and CASE-Corpora.
> Refresh CONTRIBUTE.md

- examples/crossover_heist/MSG
- examples/crossover_heist/crossover_heist.json
- examples/crossover_heist/index.html
- examples/crossover_heist/src/Makefile
- examples/crossover_heist/src/crossover_heist-acquisition.json
- examples/crossover_heist/src/crossover_heist-representing_email.json
- examples/crossover_heist/src/crossover_heist-supplemental.json
- examples/crossover_heist/src/crossover_heist-usb_hdd_links_hdd_file.json
- examples/crossover_heist/src/crossover_heist-usb_hdd_links_hdd_thebatletter_lnk.json
- examples/crossover_heist/src/crossover_heist-usb_hdd_links_hdd_wow_lnk.json
- examples/crossover_heist/src/crossover_heist-usb_hdd_links_recovery.json
- examples/crossover_heist/src/crossover_heist-usb_hdd_links_reference_relationship.json
- examples/crossover_heist/src/crossover_heist-usb_hdd_links_usb_thebatplan.json
- examples/crossover_heist/src/crossover_heist-web_browser_history_usb_file.json
- examples/crossover_heist/src/crossover_heist-web_browser_history_wow_usb.json
- examples/crossover_heist/src/crossover_heist-windows_registry_hive.json
- examples/crossover_heist/src/crossover_heist-windows_registry_key_relationship.json
- examples/crossover_heist/src/crossover_heist_base.json
- examples/crossover_heist/src/crossover_heist_json.py
- examples/crossover_heist/src/index.html.in
This patch series is similar in purpose and form to #232.
> Restructure Crossover Heist example

- examples/urgent_evidence/drafting.ttl
- examples/urgent_evidence/index.html
- examples/urgent_evidence/src/query-investigative_locations.sparql
- examples/urgent_evidence/src/urgent_evidence_base.json
- examples/urgent_evidence/urgent_evidence.json
I'm fine with this merging once CI has passed.
> Align drafting prefix IRI

- examples/urgent_evidence/urgent_evidence_validation-develop-2.0.0.ttl
- ontology/CASE-develop-2.0.0.ttl
- ontology/CASE-develop.ttl
- ontology/CASE-unstable-2.0.0.ttl
- ontology/CASE-unstable.ttl
I'm fine with this being merged once CI passes.
> Bump prerelease pointers

- Dockerfile
- Gemfile
- Gemfile.lock
- README.md
- _config.yml
- docker-compose.yml
- Adds a `Dockerfile` and `docker-compose` file for local live development and appropriate documentation
- Upgrades to Ruby 3.1
> Local Docker Build
